name: API CI

on: 
  push:
    branches: [master,develop, feature-api,refactor-folder-structure]
  pull_request: 
    branches: [master,develop, feature-api]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup and run api tests
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: |
          cd backend/api
          npm install
          npm run build --if-present
          npm test 