name: API CI

on: 
  push:
    branches: [master,develop,feature-api]
  pull_request: 
    branches: [master,develop]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup and run api tests
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
        working-directory: ./backend/api
      - run: |
          npm ci
          npm run build --if-present
          npm test 