name: Scraper CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
     defaults: 
      run:
        working-directory: ./backend/scraper


    steps:
      - uses: actions/checkout@v2
      - name: Setup and run scraper tests
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test